pipeline {
    agent any
    stages {
        stage('Build') {
    steps {
        script {
            echo "Workspace Path: ${env.WORKSPACE}"
            sh 'mvn -B -DskipTests clean package'
        }
    }
}

        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
    steps {
        
        sh 'java -jar /var/jenkins_home/workspace/Github-pipeline/target/my-app-1.0-SNAPSHOT.jar'
    }
}

        stage("Completed"){
            steps{
                echo 'Job completed!'
            }
        }
    }
}
